"use client";
import{useEffect,useMemo,useState}from"react";
import{Activity,AlertTriangle,ArrowLeft,BarChart3,Check,ChevronRight,Download,Filter,FolderKanban,Lock,RefreshCw,RotateCcw,Search,ShieldAlert,ShieldCheck,SquareX,UserPlus,Users,X}from"lucide-react";
import{supabase}from"../../../lib/supabase";

const TABS=["Overview","Jobs","Users","Workspaces","Access","Audit","Consent","Security"];
const fmt=x=>x?new Date(x).toLocaleString():"—";
const csv=v=>"""+String(v??"").replace(/"/g,'""')+""";
function Table({children}){return <div className="adminTableWrap"><table className="adminTable">{children}</table></div>}
function Pager({page,setPage,total,size=12}){const pages=Math.max(1,Math.ceil(total/size));return <div className="adminPager"><span>Page {Math.min(page+1,pages)} / {pages}</span><button disabled={page<=0} onClick={()=>setPage(Math.max(0,page-1))}>Previous</button><button disabled={page>=pages-1} onClick={()=>setPage(Math.min(pages-1,page+1))}>Next</button></div>}
function Stat({label,value,icon:Icon,kind=""}){return <div className={"adminStat "+kind}><div><span>{label}</span><strong>{value}</strong></div><Icon size={21}/></div>}

export default function AdminPage(){
 const[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[tab,setTab]=useState("Overview"),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[from,setFrom]=useState(""),[to,setTo]=useState(""),[sort,setSort]=useState("newest"),[selected,setSelected]=useState([]),[selectedWorkspace,setSelectedWorkspace]=useState(null),[selectedUser,setSelectedUser]=useState(null),[busy,setBusy]=useState(""),[toast,setToast]=useState(""),[jobPage,setJobPage]=useState(0),[userPage,setUserPage]=useState(0),[workspacePage,setWorkspacePage]=useState(0),[activityPage,setActivityPage]=useState(0),[auditPage,setAuditPage]=useState(0),[consentType,setConsentType]=useState("all"),[consentGranted,setConsentGranted]=useState("all"),[auditAction,setAuditAction]=useState("all"),[notifyOpen,setNotifyOpen]=useState(false),[notifyTitle,setNotifyTitle]=useState(""),[notifyMessage,setNotifyMessage]=useState(""),[impersonate,setImpersonate]=useState(null);
 const load=async()=>{setLoading(true);setError("");try{const{data:{session}}=await supabase.auth.getSession();if(!session?.access_token){location.href="/";return}const r=await fetch("/api/control-center",{headers:{Authorization:"Bearer "+session.access_token},cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Control center access denied.");setData(j)}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const action=async(type,body={})=>{const{data:{session}}=await supabase.auth.getSession();const r=await fetch("/api/control-center",{method:"POST",headers:{"content-type":"application/json",authorization:"Bearer "+session?.access_token},body:JSON.stringify({action:type,...body})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Action failed.");return j};
 const notify=async()=>{if(!notifyMessage.trim()||!selected.length)return;setBusy("notify");try{await action("notify_bulk",{userIds:selected,title:notifyTitle,message:notifyMessage});setToast("Notification sent.");setNotifyOpen(false);setNotifyTitle("");setNotifyMessage("");setSelected([])}catch(e){setToast(e.message)}finally{setBusy("")}};
 const retry=async id=>{setBusy(id);try{await action("retry_job",{jobId:id});setToast("Job queued for retry.");await load()}catch(e){setToast(e.message)}finally{setBusy("")}};
 const cancel=async id=>{if(!confirm("Cancel this processing job?"))return;setBusy(id);try{await action("cancel_job",{jobId:id});setToast("Job cancelled.");await load()}catch(e){setToast(e.message)}finally{setBusy("")}};
 const resolveFlag=async id=>{setBusy(id);try{await action("resolve_flag",{flagId:id});await load()}catch(e){setToast(e.message)}finally{setBusy("")}};
 const filtered=(rows,key="created_at")=>(rows||[]).filter(x=>{const q=query.trim().toLowerCase();const hay=JSON.stringify(x).toLowerCase();if(q&&!hay.includes(q))return false;if(from&&new Date(x[key]||0)<new Date(from+"T00:00:00"))return false;if(to&&new Date(x[key]||0)>new Date(to+"T23:59:59"))return false;if(status!=="all"&&x.status!==status)return false;return true}).sort((a,b)=>sort==="name"?String(a.name||a.email||"").localeCompare(String(b.name||b.email||"")):sort==="status"?String(a.status||"").localeCompare(String(b.status||"")):new Date(b[key]||0)-new Date(a[key]||0));
 const jobs=filtered(data?.jobs);const users=filtered(data?.users);const workspaces=filtered(data?.workspaces);const events=filtered(data?.events);const audit=filtered(data?.audit).filter(x=>auditAction==="all"||x.action===auditAction);const consents=filtered(data?.consents).filter(x=>(consentType==="all"||x.consent_type===consentType)&&(consentGranted==="all"||String(x.granted)===consentGranted));const pages={jobs:jobs.slice(jobPage*12,jobPage*12+12),users:users.slice(userPage*12,userPage*12+12),workspaces:workspaces.slice(workspacePage*12,workspacePage*12+12),events:events.slice(activityPage*12,activityPage*12+12),audit:audit.slice(auditPage*12,auditPage*12+12),consents:consents.slice(0,100)};
 const exportRows=(name,rows,cols)=>{const body=[cols,...rows.map(r=>cols.map(c=>r[c]))].map(r=>r.map(csv).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([body],{type:"text/csv"}));a.download=name+"-"+new Date().toISOString().slice(0,10)+".csv";a.click()};
 const exportJobs=()=>exportRows("alpha-platform-jobs",jobs,["id","status","progress","workspace_name","project_name","error","created_at","updated_at"]);
 const exportConsent=()=>exportRows("alpha-consent-ledger",consents,["id","user_id","consent_type","policy_version","granted","source","created_at"]);
 const exportUserConsent=u=>exportRows("alpha-user-consent",consents.filter(x=>x.user_id===u.id),["id","user_id","consent_type","policy_version","granted","source","created_at"]);
 const preview=async w=>{try{await action("record_impersonation",{workspaceId:w.id});setImpersonate(w)}catch(e){setToast(e.message)}};
 if(loading)return <div className="adminLoading"><ShieldCheck size={30}/><span>Loading private control center…</span></div>;
 if(error)return <div className="adminDenied"><ShieldAlert size={30}/><h2>Private admin area</h2><p>{error}</p><button className="btn" onClick={()=>location.href="/"}>Back to Alpha.ai</button></div>;
 return <div className="adminShell">
  <header className="adminHeader"><div><div className="eyebrow">ALPHA.AI · PRIVATE CONTROL CENTER</div><h1>Platform administration</h1><p>Operational visibility, access control, audit history and security signals.</p></div><div className="adminHeaderActions"><button className="btn" onClick={load}><RefreshCw size={15}/> Refresh</button><button className="btn" onClick={()=>location.href="/"}><ArrowLeft size={15}/> Workspace</button></div></header>
  {toast&&<div className="adminToast">{toast}<button onClick={()=>setToast("")}><X size={14}/></button></div>}
  {data?.configDrift?.length>0&&<div className="adminWarning"><AlertTriangle size={17}/><div><b>Control-center config drift</b><span>{data.configDrift.length} allowlisted email(s) have no active database member row.</span></div></div>}
  <div className="adminStats"><Stat label="Active jobs" value={data.stats.activeJobs} icon={Activity}/><Stat label="Failed jobs" value={data.stats.failedJobs} icon={SquareX} kind="danger"/><Stat label="Active admins" value={data.stats.activeAdmins} icon={ShieldCheck}/><Stat label="Workspaces" value={data.stats.totalWorkspaces} icon={FolderKanban}/><Stat label="Users" value={data.stats.totalUsers} icon={Users}/></div>
  <div className="adminToolbar"><div className="adminSearch"><Search size={16}/><input value={query} onChange={e=>{setQuery(e.target.value);setJobPage(0);setUserPage(0)}} placeholder="Search users, workspaces, jobs, projects…"/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option>queued</option><option>processing</option><option>completed</option><option>failed</option><option>cancelled</option></select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest</option><option value="status">Status</option><option value="name">Alphabetical</option></select><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></div>
  <nav className="adminTabs">{TABS.map(t=><button className={tab===t?"active":""} onClick={()=>setTab(t)} key={t}>{t}{t==="Security"&&data.flags?.length?<b className="adminBadge">{data.flags.length}</b>:null}</button>)}</nav>
  <main className="adminContent">
   {tab==="Overview"&&<div className="adminGrid"><section className="adminPanel adminSpan8"><div className="panelHead"><div><small>PROCESSING</small><h2>Recent jobs</h2></div><button className="btn small" onClick={()=>setTab("Jobs")}>Open Jobs <ChevronRight size={14}/></button></div><Table><thead><tr><th>Job</th><th>Status</th><th>Workspace</th><th>Progress</th><th>Updated</th></tr></thead><tbody>{pages.jobs.slice(0,8).map(j=><tr key={j.id}><td><code>{j.id.slice(0,8)}…</code><small>{j.current_stage||j.project_name||"—"}</small></td><td><span className={"statusPill "+j.status}>{j.status}</span></td><td>{j.workspace_name||"—"}</td><td>{Number(j.progress||0)}%</td><td>{fmt(j.updated_at)}</td></tr>)}</tbody></Table></section><section className="adminPanel"><div className="panelHead"><div><small>SECURITY</small><h2>Open signals</h2></div></div>{(data.flags||[]).slice(0,6).map(f=><div className="signalRow" key={f.id}><ShieldAlert size={16}/><div><b>{f.reason}</b><span>{f.severity} · {fmt(f.created_at)}</span></div></div>)}{!data.flags?.length&&<div className="adminEmpty">No open security signals.</div>}</section><section className="adminPanel adminSpan12"><div className="panelHead"><div><small>ACTIVITY</small><h2>Latest platform activity</h2></div><button className="btn small" onClick={()=>setTab("Audit")}>Full audit <ChevronRight size={14}/></button></div>{pages.events.slice(0,10).map(e=><div className="activityRow" key={e.id}><Activity size={15}/><div><b>{e.action}</b><span>{e.user_email||e.user_id||"Unknown"} · {e.workspace_name||"—"}</span></div><time>{fmt(e.created_at)}</time></div>)}</section></div>}
   {tab==="Jobs"&&<section className="adminPanel"><div className="panelHead"><div><small>ALL PROCESSING</small><h2>Jobs</h2><span>{jobs.length} matching jobs</span></div><button className="btn" onClick={exportJobs}><Download size={15}/> CSV</button></div><Table><thead><tr><th>Job</th><th>Status</th><th>Workspace / Project</th><th>Progress</th><th>Error</th><th>Actions</th></tr></thead><tbody>{pages.jobs.map(j=><tr key={j.id}><td><code>{j.id.slice(0,12)}…</code><small>{j.current_stage||"—"}</small></td><td><span className={"statusPill "+j.status}>{j.status}</span></td><td>{j.workspace_name}<small>{j.project_name}</small></td><td>{j.progress||0}%</td><td className="errorCell">{j.error||"—"}</td><td><div className="rowActions">{j.status==="failed"&&<button disabled={busy===j.id} onClick={()=>retry(j.id)} title="Retry"><RotateCcw size={14}/></button>}{["queued","processing"].includes(j.status)&&<button disabled={busy===j.id} onClick={()=>cancel(j.id)} title="Cancel"><SquareX size={14}/></button>}</div></td></tr>)}</tbody></Table><Pager page={jobPage} setPage={setJobPage} total={jobs.length}/></section>}
   {tab==="Users"&&<section className="adminPanel"><div className="panelHead"><div><small>AUTH USERS</small><h2>Users</h2></div><button className="btn" disabled={!selected.length} onClick={()=>setNotifyOpen(true)}><BellIcon/> Notify selected</button></div><Table><thead><tr><th></th><th>User</th><th>Last sign-in</th><th>Confirmed</th><th>Owned workspaces</th><th>Actions</th></tr></thead><tbody>{pages.users.map(u=><tr key={u.id}><td><input type="checkbox" checked={selected.includes(u.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,u.id]:v.filter(x=>x!==u.id))}/></td><td><b>{u.profile?.full_name||u.email}</b><small>{u.email}</small></td><td>{fmt(u.last_sign_in_at)}</td><td>{u.confirmed_at?"Yes":"No"}</td><td>{u.workspaces?.length||0}</td><td><button className="outlineBtn" onClick={()=>setSelectedUser(u)}>Details</button></td></tr>)}</tbody></Table><Pager page={userPage} setPage={setUserPage} total={users.length}/></section>}
   {tab==="Workspaces"&&<section className="adminPanel"><div className="panelHead"><div><small>PLATFORM</small><h2>All workspaces</h2></div></div><Table><thead><tr><th>Workspace</th><th>Owner</th><th>Projects</th><th>Created</th><th>Support</th></tr></thead><tbody>{pages.workspaces.map(w=><tr key={w.id}><td><b>{w.name}</b><small>{w.id}</small></td><td>{w.owner_email||"—"}</td><td>{w.project_count}</td><td>{fmt(w.created_at)}</td><td><button className="outlineBtn" onClick={()=>preview(w)}>Read-only preview</button></td></tr>)}</tbody></Table><Pager page={workspacePage} setPage={setWorkspacePage} total={workspaces.length}/>{selectedWorkspace&&<div/>}</section>}
   {tab==="Access"&&<section className="adminGrid"><section className="adminPanel adminSpan8"><div className="panelHead"><div><small>CONTROL CENTER</small><h2>Admin access</h2></div><span>{data.members.filter(x=>x.active).length} active</span></div>{data.members.map(m=><div className="memberRow" key={m.id}><ShieldCheck size={17}/><div><b>{m.email}</b><span>{m.role} · last active {fmt(m.last_seen_at)}</span></div><span className={m.active?"statusPill completed":"statusPill failed"}>{m.active?"active":"revoked"}</span>{m.active&&m.email!==data.currentAdmin&&<button className="outlineBtn" onClick={async()=>{const email=prompt("Type this email to confirm revocation: "+m.email,"");if(email===null)return;setBusy(m.email);try{await action("revoke_access",{email:m.email,confirmEmail:email});setToast("Access revoked.");await load()}catch(e){setToast(e.message)}finally{setBusy("")}}}>Revoke</button>}</div>)}</section><section className="adminPanel"><div className="panelHead"><div><small>GRANT</small><h2>Add admin</h2></div></div><GrantAccess onDone={async()=>{await load()}} action={action} setToast={setToast}/></section></section>}
   {tab==="Audit"&&<section className="adminPanel"><div className="panelHead"><div><small>ACTIVITY + AUDIT</small><h2>Audit history</h2></div><select value={auditAction} onChange={e=>setAuditAction(e.target.value)}><option value="all">All actions</option>{[...new Set((data.audit||[]).map(x=>x.action))].map(a=><option key={a}>{a}</option>)}</select></div><Table><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Workspace</th><th>Metadata</th></tr></thead><tbody>{pages.audit.map(a=><tr key={a.id}><td>{fmt(a.created_at)}</td><td>{a.user_email||a.user_id||"System"}</td><td>{a.action}</td><td>{a.workspace_name||"—"}</td><td><code>{JSON.stringify(a.metadata||{})}</code></td></tr>)}</tbody></Table><Pager page={auditPage} setPage={setAuditPage} total={audit.length}/></section>}
   {tab==="Consent"&&<section className="adminPanel"><div className="panelHead"><div><small>COMPLIANCE</small><h2>Consent ledger</h2></div><div className="panelFilters"><select value={consentType} onChange={e=>setConsentType(e.target.value)}><option value="all">All types</option>{[...new Set((data.consents||[]).map(x=>x.consent_type))].map(x=><option key={x}>{x}</option>)}</select><select value={consentGranted} onChange={e=>setConsentGranted(e.target.value)}><option value="all">Granted + declined</option><option value="true">Granted</option><option value="false">Declined</option></select><button className="btn small" onClick={exportConsent}><Download size={14}/> Export</button></div></div><Table><thead><tr><th>Time</th><th>User</th><th>Type</th><th>Policy</th><th>Decision</th><th>Source</th><th/></tr></thead><tbody>{pages.consents.map(c=><tr key={c.id}><td>{fmt(c.created_at)}</td><td>{users.find(u=>u.id===c.user_id)?.email||c.user_id}</td><td>{c.consent_type}</td><td>{c.policy_version||"—"}</td><td>{c.granted?"Granted":"Declined"}</td><td>{c.source}</td><td><button className="outlineBtn" onClick={()=>{const u=users.find(u=>u.id===c.user_id);if(u)exportUserConsent(u)}}>User CSV</button></td></tr>)}</tbody></Table></section>}
   {tab==="Security"&&<section className="adminPanel"><div className="panelHead"><div><small>BEHAVIORAL SIGNALS</small><h2>Security flags</h2><p>Flags are evidence-based signals, not accusations. They surface unusual activity for human review.</p></div></div>{(data.flags||[]).map(f=><div className="flagCard" key={f.id}><div className={"flagSeverity "+f.severity}>{f.severity}</div><div className="flagMain"><b>{f.reason}</b><span>{f.signal} · user {f.user_id||"unknown"} · {fmt(f.created_at)}</span><code>{JSON.stringify(f.evidence||{})}</code></div><button className="outlineBtn" disabled={busy===f.id} onClick={()=>resolveFlag(f.id)}>Resolve</button></div>)}{!data.flags?.length&&<div className="adminEmpty"><Check size={18}/> No open flags.</div>}</section>}
  </main>
  {selectedUser&&<div className="adminModal" onMouseDown={()=>setSelectedUser(null)}><div className="adminModalCard" onMouseDown={e=>e.stopPropagation()}><button className="modalClose" onClick={()=>setSelectedUser(null)}><X/></button><div className="eyebrow">USER DETAIL</div><h2>{selectedUser.profile?.full_name||selectedUser.email}</h2><p>{selectedUser.email}</p><div className="detailGrid"><div><b>Last sign-in</b><span>{fmt(selectedUser.last_sign_in_at)}</span></div><div><b>Confirmed</b><span>{selectedUser.confirmed_at?"Yes":"No"}</span></div><div><b>Created</b><span>{fmt(selectedUser.created_at)}</span></div><div><b>Owned workspaces</b><span>{selectedUser.workspaces?.map(w=>w.name).join(", ")||"None"}</span></div></div><h3>Consent history</h3>{consents.filter(c=>c.user_id===selectedUser.id).slice(0,30).map(c=><div className="detailRow" key={c.id}><span>{c.consent_type}</span><b>{c.granted?"Granted":"Declined"}</b><time>{fmt(c.created_at)}</time></div>)}<button className="btn" onClick={()=>exportUserConsent(selectedUser)}><Download size={15}/> Export consent history</button></div></div>}
  {impersonate&&<div className="adminModal" onMouseDown={()=>setImpersonate(null)}><div className="adminModalCard wide" onMouseDown={e=>e.stopPropagation()}><button className="modalClose" onClick={()=>setImpersonate(null)}><X/></button><div className="eyebrow">READ-ONLY SUPPORT PREVIEW</div><h2>{impersonate.name}</h2><p>No write actions are available. Opening this preview is logged.</p><div className="detailGrid"><div><b>Owner</b><span>{impersonate.owner_email}</span></div><div><b>Projects</b><span>{impersonate.project_count}</span></div><div><b>Created</b><span>{fmt(impersonate.created_at)}</span></div></div><h3>Projects in workspace</h3>{(data.projects||[]).filter(p=>p.workspace_id===impersonate.id).map(p=><div className="detailRow" key={p.id}><span>{p.name}</span><b>{p.status||"draft"}</b><time>{fmt(p.updated_at||p.created_at)}</time></div>)}</div></div>}
  {notifyOpen&&<div className="adminModal" onMouseDown={()=>setNotifyOpen(false)}><div className="adminModalCard" onMouseDown={e=>e.stopPropagation()}><button className="modalClose" onClick={()=>setNotifyOpen(false)}><X/></button><div className="eyebrow">BULK NOTIFICATION</div><h2>Notify {selected.length} user(s)</h2><input className="input" placeholder="Title" value={notifyTitle} onChange={e=>setNotifyTitle(e.target.value)}/><textarea className="input" rows="6" placeholder="Message" value={notifyMessage} onChange={e=>setNotifyMessage(e.target.value)}/><button className="btn primary full" disabled={busy==="notify"} onClick={notify}>{busy==="notify"?"Sending…":"Send notification"}</button></div></div>}
 </div>
}
function GrantAccess({action,onDone,setToast}){const[email,setEmail]=useState(""),[role,setRole]=useState("viewer"),[busy,setBusy]=useState(false);return <div className="grantBox"><input className="input" type="email" placeholder="admin@company.com" value={email} onChange={e=>setEmail(e.target.value)}/><select className="input" value={role} onChange={e=>setRole(e.target.value)}><option value="viewer">Viewer</option><option value="admin">Admin</option></select><button className="btn primary full" disabled={busy} onClick={async()=>{if(!email.trim())return; if(!confirm("Grant control-center access to "+email+"?"))return;setBusy(true);try{const j=await action("grant_access",{email,role});setToast(j.invited?"Access granted and invitation sent.":"Access granted.");setEmail("");await onDone()}catch(e){setToast(e.message)}finally{setBusy(false)}}}><UserPlus size={15}/> Grant access</button></div>}
function BellIcon(){return <Activity size={15}/>}
