"use client";
import{useEffect,useRef,useState}from"react";
import{Images,Loader2,ExternalLink,Check,RefreshCw}from"lucide-react";
import{supabase}from"../lib/supabase";

const CLIENT_ID=process.env.NEXT_PUBLIC_GOOGLE_PHOTOS_CLIENT_ID||process.env.NEXT_PUBLIC_GOOGLE_DRIVE_CLIENT_ID||"";
const SCOPE="https://www.googleapis.com/auth/photospicker.mediaitems.readonly";

export default function GooglePhotosPicker({workspaceId,userId,onImported,onError}){
 const[token,setToken]=useState("");const[session,setSession]=useState(null);const[items,setItems]=useState([]);const[loading,setLoading]=useState(false);const[connecting,setConnecting]=useState(false);const clientRef=useRef(null);const timerRef=useRef(null);
 useEffect(()=>()=>{if(timerRef.current)clearTimeout(timerRef.current)},[]);
 useEffect(()=>{if(typeof window==="undefined"||!CLIENT_ID)return;const existing=document.querySelector('script[src="https://accounts.google.com/gsi/client"]');const init=()=>{if(window.google?.accounts?.oauth2)clientRef.current=window.google.accounts.oauth2.initTokenClient({client_id:CLIENT_ID,scope:SCOPE,callback:()=>{}})};if(existing){init();return}const s=document.createElement("script");s.src="https://accounts.google.com/gsi/client";s.async=true;s.defer=true;s.onload=init;document.head.appendChild(s)},[]);
 const authorize=()=>{if(!CLIENT_ID)return onError?.("Google Photos is not configured. Add NEXT_PUBLIC_GOOGLE_PHOTOS_CLIENT_ID (or reuse the Drive client ID) in Vercel.");if(!clientRef.current)return onError?.("Google authorization is still loading.");clientRef.current.callback=async r=>{if(r.error)return onError?.("Google Photos authorization was not completed.");setToken(r.access_token);await createPicker(r.access_token)};clientRef.current.requestAccessToken({prompt:token?"":"consent"})};
 const createPicker=async t=>{setConnecting(true);try{const r=await fetch("https://photospicker.googleapis.com/v1/sessions",{method:"POST",headers:{Authorization:"Bearer "+t,"Content-Type":"application/json"},body:JSON.stringify({pickingConfig:{maxItemCount:"1"}})});const d=await r.json();if(!r.ok)throw new Error(d.error?.message||"Unable to create Google Photos picker session.");setSession(d);window.open(d.pickerUri+"/autoclose","_blank","noopener,noreferrer");await pollSession(t,d.id,Number(String(d.pollingConfig?.pollInterval||"3s").replace("s",""))*1000||3000,Number(String(d.pollingConfig?.timeoutIn||"300s").replace("s",""))*1000||300000)}catch(e){onError?.(e.message)}finally{setConnecting(false)}};
 const pollSession=async(t,id,delay,timeout)=>{const deadline=Date.now()+timeout;while(Date.now()<deadline){await new Promise(r=>{timerRef.current=setTimeout(r,Math.max(1500,delay))});const r=await fetch("https://photospicker.googleapis.com/v1/sessions/"+encodeURIComponent(id),{headers:{Authorization:"Bearer "+t}});const d=await r.json();if(!r.ok)throw new Error(d.error?.message||"Google Photos picker session failed.");if(d.mediaItemsSet){const lr=await fetch("https://photospicker.googleapis.com/v1/mediaItems?sessionId="+encodeURIComponent(id)+"&pageSize=100",{headers:{Authorization:"Bearer "+t}});const ld=await lr.json();if(!lr.ok)throw new Error(ld.error?.message||"Unable to read selected Google Photos items.");const selected=(ld.mediaItems||[]).filter(x=>x.mediaFile?.mimeType?.startsWith("video/"));if(!selected.length)throw new Error("Select a video in Google Photos.");setItems(selected);return selected}}throw new Error("Google Photos selection timed out. Start a new selection.")};
 const importItem=async item=>{setLoading(true);try{const{data:{session:authSession}}=await supabase.auth.getSession();const r=await fetch("/api/google-photos/import",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+(authSession?.access_token||"")},body:JSON.stringify({accessToken:token,item,workspaceId,userId})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Google Photos import failed.");onImported?.(d)}catch(e){onError?.(e.message)}finally{setLoading(false)}};
 return <div className="driveBrowser">
  {!session&&!items.length?<div className="driveConnect"><div className="driveLogo"><Images size={26}/></div><h3>Import from Google Photos</h3><p>Choose a video in Google Photos, then Alpha.ai downloads only the item you selected.</p><button className="btn primary" onClick={authorize} disabled={connecting}>{connecting?<><Loader2 className="spin" size={15}/> Opening Google Photos…</>:<><Images size={16}/> Choose from Google Photos</>}</button></div>:
  <><div className="driveToolbar"><div><b>{items.length} selected video{items.length===1?"":"s"}</b></div><button className="btn" onClick={authorize}><RefreshCw size={15}/> Choose again</button></div><div className="driveFiles">{items.map(item=><button key={item.id} className="driveFile selected" onClick={()=>importItem(item)} disabled={loading}><div className="driveFileIcon"><Images size={20}/></div><div><b>{item.mediaFile?.filename||"Google Photos video"}</b><small>{item.mediaFile?.mimeType||"video"} · selected item</small></div>{loading?<Loader2 className="spin" size={18}/>:<Check size={18}/>}</button>)}</div><div className="driveFooter"><span>Only the selected Google Photos video is imported.</span><ExternalLink size={14}/></div></>}
 </div>
}