"use client";
import{useEffect,useMemo,useState}from"react";
import{supabase}from"../../lib/supabase";
import{Activity,AlertTriangle,Bell,CheckCircle2,Clock,Eye,KeyRound,Mail,RefreshCw,ShieldCheck,Users,UserPlus,X}from"lucide-react";
import"./control-center.css";
export default function ControlCenter(){
 const[data,setData]=useState(null),[tab,setTab]=useState("overview"),[busy,setBusy]=useState(true),[error,setError]=useState(""),[email,setEmail]=useState(""),[memberRole,setMemberRole]=useState("viewer"),[selectedUser,setSelectedUser]=useState(""),[notice,setNotice]=useState(""),[noticeMsg,setNoticeMsg]=useState(""),[query,setQuery]=useState("");
 const load=async()=>{setBusy(true);setError("");try{const{data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error("Authentication required.");const r=await fetch("/api/control-center",{headers:{authorization:"Bearer "+session.access_token},cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error||"Control center unavailable.");setData(b)}catch(e){setError(e.message)}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const act=async(body)=>{const{data:{session}}=await supabase.auth.getSession();const r=await fetch("/api/control-center",{method:"POST",headers:{"content-type":"application/json",authorization:"Bearer "+session.access_token},body:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw new Error(b.error||"Action failed.");return b};
 const users=data?.users||[], filtered=users.filter(u=>JSON.stringify(u).toLowerCase().includes(query.toLowerCase()));
 const stats=useMemo(()=>({users:users.length,workspaces:data?.workspaces?.length||0,projects:data?.projects?.length||0,jobs:data?.jobs?.length||0,events:data?.events?.length||0}),[data,users.length]);
 if(busy)return <div className="ccLoading"><RefreshCw className="spin"/><span>Opening private control center…</span></div>;
 if(error)return <div className="ccLoading"><AlertTriangle/><div><h2>Control center unavailable</h2><p>{error}</p><button className="ccBtn" onClick={load}>Retry</button></div></div>;
 return <div className="controlCenter"><header className="ccHeader"><div><div className="ccEyebrow"><ShieldCheck size={14}/> PRIVATE OPERATIONS</div><h1>Alpha Control Center</h1><p>Owner-authorized operations, account activity, consent records and workspace health.</p></div><button className="ccBtn" onClick={load}><RefreshCw size={15}/> Refresh</button></header>
 <div className="ccSecurity"><ShieldCheck size={16}/><span>Server-authorized access only. This console is not linked from the user workspace. Data shown here is limited to information Alpha.ai has a documented basis to collect.</span></div>
 <nav className="ccTabs">{[["overview","Overview"],["users","Users"],["activity","Activity"],["consent","Consent"],["access","Access"],["notifications","Notifications"]].map(([id,label])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav>
 {tab==="overview"&&<><div className="ccStats">{Object.entries(stats).map(([k,v])=><div className="ccStat" key={k}><small>{k.toUpperCase()}</small><b>{v}</b></div>)}</div><div className="ccGrid"><section className="ccCard ccWide"><div className="ccCardHead"><div><small>RECENT ACTIVITY</small><h2>Live account events</h2></div><Activity size={18}/></div>{(data?.events||[]).slice(0,12).map(e=><EventRow key={e.id} e={e}/>)}</section><section className="ccCard"><div className="ccCardHead"><div><small>PROCESSING</small><h2>Job health</h2></div><Clock size={18}/></div>{(data?.jobs||[]).slice(0,10).map(j=><div className="ccLine" key={j.id}><span>{j.status}</span><b>{j.progress||0}%</b><small>{new Date(j.created_at).toLocaleString()}</small></div>)}</section></div></>}
 {tab==="users"&&<section className="ccCard"><div className="ccToolbar"><input placeholder="Search users by email, name…" value={query} onChange={e=>setQuery(e.target.value)}/><span>{filtered.length} users</span></div><div className="ccTable">{filtered.map(u=><button className="ccUserRow" key={u.id} onClick={()=>setSelectedUser(u.id)}><span className="ccAvatar">{(u.profile?.full_name||u.email||"?").slice(0,1).toUpperCase()}</span><span><b>{u.profile?.full_name||u.email||"Unnamed user"}</b><small>{u.email} · joined {new Date(u.created_at).toLocaleDateString()}</small></span><span><small>Last sign-in</small>{u.last_sign_in_at?new Date(u.last_sign_in_at).toLocaleString():"Never"}</span><Eye size={15}/></button>)}</div></section>}
 {tab==="activity"&&<section className="ccCard"><div className="ccCardHead"><div><small>AUDIT + ACTIVITY</small><h2>Everything recorded by Alpha.ai</h2></div></div>{[...(data?.events||[]).map(e=>({...e,_kind:"activity"})),...(data?.audit||[]).map(e=>({...e,_kind:"audit",user_email:(users.find(u=>u.id===e.user_id)||{}).email||""}))].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,100).map(e=><EventRow key={e._kind+e.id} e={e}/>)}</section>}
 {tab==="consent"&&<section className="ccCard"><div className="ccCardHead"><div><small>PRIVACY LEDGER</small><h2>Policy and cookie consent records</h2><p>Only consent decisions and policy versions are retained here — never raw browser cookies or unrelated browsing contents.</p></div></div>{(data?.consents||[]).map(c=><div className="ccConsent" key={c.id}><span className={c.granted?"ok":"off"}>{c.granted?"Granted":"Declined"}</span><b>{c.consent_type}</b><span>v{c.policy_version||"unspecified"}</span><span>{c.source}</span><small>{new Date(c.created_at).toLocaleString()}</small></div>)}</section>}
 {tab==="access"&&<section className="ccCard"><div className="ccCardHead"><div><small>TEAM ACCESS</small><h2>Grant private-console access</h2><p>Add a specific email as an authorized control-center teammate. They must authenticate with that account.</p></div><KeyRound size={18}/></div><div className="ccInvite"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="teammate@example.com"/><select value={memberRole} onChange={e=>setMemberRole(e.target.value)}><option value="viewer">Viewer</option><option value="admin">Admin</option></select><button className="ccBtn primary" onClick={async()=>{try{const b=await act({action:"grant_access",email,role:memberRole});setNotice(b.invited?"Invitation email sent.":"Access granted for this account.");setEmail("");await load()}catch(e){setNotice(e.message)}}}><UserPlus size={15}/> Grant access</button></div><div className="ccTable">{(data?.members||[]).map(m=><div className="ccMember" key={m.id}><span><Mail size={15}/><b>{m.email}</b></span><span>{m.role}</span><span className={m.active?"live":"off"}>{m.active?"Active":"Revoked"}</span>{m.email.toLowerCase()!==((data?.currentUserEmail||"").toLowerCase())&&<button className="iconBtn" onClick={async()=>{try{await act({action:"revoke_access",email:m.email});await load()}catch(e){setNotice(e.message)}}}><X size={15}/></button>}</div>)}</div>{notice&&<div className="ccNotice">{notice}</div>}</section>}
 {tab==="notifications"&&<section className="ccCard"><div className="ccCardHead"><div><small>USER NOTIFICATIONS</small><h2>Send an in-app notification</h2></div><Bell size={18}/></div><div className="ccInvite"><select value={selectedUser} onChange={e=>setSelectedUser(e.target.value)}><option value="">Choose user</option>{users.map(u=><option key={u.id} value={u.id}>{u.email}</option>)}</select><input value={notice} onChange={e=>setNotice(e.target.value)} placeholder="Notification title"/><input value={noticeMsg} onChange={e=>setNoticeMsg(e.target.value)} placeholder="Message"/><button className="ccBtn primary" onClick={async()=>{try{await act({action:"notify",userId:selectedUser,title:notice,message:noticeMsg});setNotice("Notification sent.");setNoticeMsg("")}catch(e){setNotice(e.message)}}}><Bell size={15}/> Send</button></div><div className="ccTable">{(data?.notifications||[]).map(n=><div className="ccLine" key={n.id}><b>{n.title}</b><span>{n.message}</span><small>{new Date(n.created_at).toLocaleString()}</small></div>)}</div></section>}
 {selectedUser&&<div className="ccModal" onClick={()=>setSelectedUser("")}><div className="ccModalCard" onClick={e=>e.stopPropagation()}><button className="iconBtn" onClick={()=>setSelectedUser("")}><X/></button>{(()=>{const u=users.find(x=>x.id===selectedUser);if(!u)return null;const ev=(data?.events||[]).filter(x=>x.user_id===u.id);const co=(data?.consents||[]).filter(x=>x.user_id===u.id);return <><div className="ccAvatar big">{(u.profile?.full_name||u.email||"?").slice(0,1).toUpperCase()}</div><h2>{u.profile?.full_name||"User details"}</h2><p>{u.email}</p><div className="ccDetailGrid"><span>Created<strong>{new Date(u.created_at).toLocaleString()}</strong></span><span>Last sign-in<strong>{u.last_sign_in_at?new Date(u.last_sign_in_at).toLocaleString():"Never"}</strong></span><span>Workspaces<strong>{u.workspaces.length}</strong></span><span>Confirmed<strong>{u.confirmed_at?"Yes":"No"}</strong></span></div><h3>Recent activity</h3>{ev.slice(0,20).map(e=><EventRow key={e.id} e={e}/>)}<h3>Consent history</h3>{co.slice(0,20).map(c=><div className="ccConsent" key={c.id}><span className={c.granted?"ok":"off"}>{c.granted?"Granted":"Declined"}</span><b>{c.consent_type}</b><small>{new Date(c.created_at).toLocaleString()}</small></div>)}</>})()}</div></div>}</div>
}
function EventRow({e}){return <div className="ccEvent"><Activity size={14}/><span><b>{e.action}</b><small>{e.user_email||"system"}{e.workspace_name?" · "+e.workspace_name:""}{e.entity_type?" · "+e.entity_type:""}</small></span><time>{new Date(e.created_at).toLocaleString()}</time></div>}
